### ISSUE TITLE
CPU Cores utilization problem

### ISSUE THREAD

**Issue by junaid-malik-confiz** [steel/sprockets-derailleur#18]
Hi,

We have 4 cores on local and when we use this gem with default setting, it uses all 3 cores and we can see activity using top/htop. But when we run this on production machine with 12 cores, it show that it is using the 12 cores but when we check using htop, it shows 3 core busy and rest are idle. On production machine we have Ruby 2.1.2. Can you tell us if there is something to tune to finish asset compile task in 1/2 minutes using maximum cores.

Regards,
Junaid

**Comment by steel** [comment]
All this gem does is go through each file you need compiled and dole it out to a worker. How many files are you compiling? If its 1 monolithic file, then having more cores will not help.
