### ISSUE TITLE
NoMethodError: undefined method `times' for nil:NilClass

### ISSUE THREAD

**Issue by Preen** [steel/sprockets-derailleur#19]
$ RAILS_ENV=production rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
W, [2015-11-06T01:10:57.852335 #18236]  WARN -- : Initializing  workers
rake aborted!
NoMethodError: undefined method `times' for nil:NilClass
/Users/--/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sprockets-derailleur-0.0.1/lib/sprockets-derailleur.rb:23:in `block in compile'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sprockets-derailleur-0.0.1/lib/sprockets-derailleur.rb:16:in `compile'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sprockets-3.4.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/--/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/--/.rbenv/versions/2.2.3/bin/rake:33:in `<main>'
Tasks: TOP => assets:precompile'''

**Comment by clod81** [comment]
same here :+1:

**Comment by steel** [comment]
It looks like the gem wasn't able to determine how many cores you have. `Initializing workers` should say `Initializing <number> workers`

**Comment by steel** [comment]
Can you take a look here and see what is broken in your environment? https://github.com/steel/sprockets-derailleur/blob/master/lib/sprockets-derailleur.rb#L6

**Comment by ttakezawa** [comment]
Same here.
I use sprockets 3.5.2, but the latest derailleur has dependency `gem.add_dependency 'sprockets', "~>2"`
Therefore, Rubygems resolve `sprockets-derailleur (0.0.1)`.

**Comment by pensan** [comment]
Adding `gem 'sprockets-derailleur', '0.0.9'` in the Gemfile solved the problem for me, thanks.
