### ISSUE TITLE
Does this gem support sprockets 3?

### ISSUE THREAD

**Issue by PikachuEXE** [steel/sprockets-derailleur#21]
Or does it matter anymore in sprockets 3?

**Comment by amolpujari** [comment]
+1

**Comment by steel** [comment]
I've stopped using this gem so not sure if it works in Sprockets 3 or not.

**Comment by PikachuEXE** [comment]
@steel 
Do you have the same performance after removing this gem?

**Comment by CodeMonkeySteve** [comment]
Definitely does not work with Sprockets v3.6, lots of 'undefined method' errors.  Apparently Sprockets changed quite a lot since v2.

**Comment by steel** [comment]
Thanks for the update!
