### ISSUE TITLE
Processes seemed to become stale.

### ISSUE THREAD

**Issue by evertonfraga** [steel/sprockets-derailleur#23]
Hi all, I'm having some trouble to compile assets.

First, ruby process (PID xxxx90) spawns 4 workers. on the following 10 minutes the processes look   like this:

> # 93 - 0% CPU
> # 94 - 0% CPU
> # 95 - 0% CPU
> # 96 - 100% CPU

After #91 has completed compiling about 18 assets (from hundreds), it stalls, as shown below:
![image](https://cloud.githubusercontent.com/assets/47108/17487229/502a3492-5d6a-11e6-928b-c6f7896a87f4.png)

We can see the CPU time on each process and infer that, not only the tasks might have been assigned to only one process, but they seemed to become stale.

I was using 0.9 and upgraded to 0.10. My machine is a (brand new) macbook pro quad-core.

**Comment by steel** [comment]
How many files are you compiling? Is it getting stuck at a particular file? Try lowering the log level and see if it reveals anything.
